services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_DB: collectodb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgAdmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
    - db
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
volumes:
  pgdata:
        
  